print("Welcome to SpyChat")
spy_name=input("Enter your name: ")
spy_salutation=input("what should we call you "+spy_name+" (Mr. or Ms.)? ")
print("Glad to have you here "+spy_salutation+"."+spy_name)
print("Alright "+spy_salutation+"."+spy_name+" We would like to know a little bit more about you...")
spy_agency=input("Enter your spying agency name: ")
spy_experience=input("for how many years you are working as a spy? ")
spy_rating=input("what is your rating(out of 5)? ")
print("thanks for telling the information about you...")
print(spy_salutation+"."+spy_name+" you are from "+spy_agency+" with a handful experience of "+spy_experience+" years and a rating of "+spy_rating)
